# Basic
title: æ˜¯æˆ‘å·åƒçš„ğŸ—
subtitle: ""
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: èµ°ï½å»ä¼¤å®³ä»–ä»¬çš„æ„Ÿæƒ…
creator: <a href="https://yinheng.me">Maple Yin</a>

url: "https://blog.yinheng.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: é¦–é¡µ
    description: Home Page

# Navigation buttons in the front page.
nav:
    - {title: ç¢ç¢å¿µ, description: talk, url: '/2021/05/talk'}
    - {title: IELTS, description: IELTS, url: '/ielts/'}
    - {title: Material, description: material, url: '/material/'}
    - {title: Reading, description: reading, url: '/reading/'}
    # - {title: å…³äº, description: about, url: '/2019/06/about'}
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    # github: onevcat
    # twitter: onevcat
    # gplus: 107108267983477358170
    # mail: onev@onevcat.com

# Google Analytics
ga:
    id: G-5TZWCN5VS3

#  Collections
collections:
    ielts:
        output: true
    talks:
        output: true
    material:
        output: true
    reading:
        output: true